//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2022/11/25 21:17:13
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WebAPI.Models
{
    public class AdminUser
    {

        public AdminUser()
        {
          
        }

        public int Ad_ID { get; set; }

        public  string Ad_Name { get; set; }

        public string Ad_Surname { get; set; }

        public string Ad_Email_Address { get; set; }

        public int Ad_Cell_Number { get; set; }

        public string Ad_Password { get; set; }

        public string Ad_Role { get; set; }
    }

}
